### ISSUE TITLE
BIOS doesn’t wanna boot off of USB, not a bootable partion

### ISSUE THREAD

**Issue by marleyqp** [Watking01/bootm8#1]
USB doesn’t even show up in BIOS or my boot manager so can’t get into it

**Comment by SarKaa** [comment]
Why are you using this, it isn’t finished, and it’s not meant to be used, if you want to use a checkra1n iso, use this https://github.com/Watking01/psc-checkn1x/releases/tag/1.1.0 
I will be pushing an update to this repo so that you can use a much better version of this

**Comment by marleyqp** [comment]
Okay i didn’t know 😔

**Comment by marleyqp** [comment]
Also that is having the same problem

**Comment by marleyqp** [comment]
Actually, it boots, it says ‘Welcome to GRUB’ then says error: unknown fileystem

**Comment by SarKaa** [comment]
> Actually, it boots, it says ‘Welcome to GRUB’ then says error: unknown fileystem

Ok but now you should use this repo
https://github.com/Watking01/bootm8/releases/tag/1.0.0

I am sorry that you had problems, but my testing has shown that this does work, are you sure your computer is compatable

**Comment by marleyqp** [comment]
Trying that release now and i will let you know.

**Comment by SarKaa** [comment]
> Trying that release now and i will let you know.

Also just make sure you are following all the right instructions
They have changed several times over the past few days, such as making sure that your using rufus, which is definitely working on my two test  computers and one compiter virtualized on my phone

**Comment by SarKaa** [comment]
Oh and I forgot to mention that some errors will occur, just wait about a minute, if it still doesn't work i'll look into it further

**Comment by marleyqp** [comment]
do you have an iPhone? cause i can test on my phone to see if it’s my computer. Also, in rEFIND Boot Manager, for some reason it says ‘Boot Mac OS X’ and then it says the ‘Welcome to GRUB’ then a bunch of ‘unknown filesystem’ sane thing with booting from BIOS

**Comment by marleyqp** [comment]
Tried Rufus (Windows 10) and woeusb/balenaetcher (Ubuntu 18.04)

**Comment by marleyqp** [comment]
And it seems like the iso is not bootable

**Comment by marleyqp** [comment]
But that’s what PowerISO said so idk

**Comment by SarKaa** [comment]
> do you have an iPhone? cause i can test on my phone to see if it’s my computer. Also, in rEFIND Boot Manager, for some reason it says ‘Boot Mac OS X’ and then it says the ‘Welcome to GRUB’ then a bunch of ‘unknown filesystem’ sane thing with booting from BIOS

I don't know what thats about, but yes i do have an iphone, and i tested it with this
https://github.com/utmapp/UTM

**Comment by SarKaa** [comment]
> And it seems like the iso is not bootable

Its not about the partition being bootable, thats why it doesnt work from etcher. Rufus makes it bootable when you write the iso, oh i think the problem is that you might not be using mbr as your partition scheme

**Comment by SarKaa** [comment]
Its most likely a compatability issue, as it worked on other people's computers as well, and i am 100% certain that it isnt a problem with the partition being bootable or not

**Comment by marleyqp** [comment]
in UTM what settings? because that also is saying not a bootable image

**Comment by marleyqp** [comment]
i’m genuinely curious as to what the hell is going on. checkn1x, bootra1n and livera1n works on my system. maybe i’ll try that in UTM

**Comment by marleyqp** [comment]
bootra1n works on my laptop and in UTM. 🤨

**Comment by SarKaa** [comment]
I am planning to release another version tody, and I made another utm vm but now it gets stuck at welcome to GRUB, don’t worry this was bound to happen as I haven’t properly released this y

**Comment by marleyqp** [comment]
That’s exactly what’s happening on my laptop. Best wishes!

**Comment by SarKaa** [comment]
Sorry about the delay but I am making a complete rewrite, so it might take a while

**Comment by marleyqp** [comment]
Take as much time as you need

**Comment by SarKaa** [comment]
Could you do me a favour and try out the new pre-release, thanks

**Comment by SarKaa** [comment]
I don’t think it works on utm, but could you try in your computer

**Comment by marleyqp** [comment]
I’m happy to report, that, it boots! and works! the only problem is, when you say ‘enter p into the boot arguments’ it doesn’t work. so i had to use the cli. but the problem is you can’t get out of that in checkn1x. because your stuck. so i had to boot into pongo, restart, then type android into terminal. it works, but not great. and that’s not your fault. mostly just the way it works/checkra1n.

**Comment by SarKaa** [comment]
What do you mean it doesn't work,what is the problem

**Comment by SarKaa** [comment]
I think you can just exit by typing control c, and try it with the new release

**Comment by SarKaa** [comment]
Could you try the new release

**Comment by marleyqp** [comment]
Of course

**Comment by marleyqp** [comment]
Getting another Grub error
error: invalid arch-independent ELF magic.
what?! lol

**Comment by SarKaa** [comment]
Ok will try to fix

**Comment by SarKaa** [comment]
It worked when I did it, can you retry

**Comment by marleyqp** [comment]
I will try, also latest checkn1x didn’t work latest release but did before. Don’t know what’s going on

**Comment by SarKaa** [comment]
I think it’s probably your computer, as this is the most stable release
