### ISSUE TITLE
Orca screen reader support for blind users

### ISSUE THREAD

**Issue by saleem202** [Watking01/bootm8#12]
Hello, I was wondering if Orca screen reader support can be added for blind users, as this will really help them to perform all the tasks independently.
For more information about Orca see https://help.gnome.org/users/orca/stable/
Orca GitHub page is https://github.com/GNOME/orca

**Comment by SarKaa** [comment]
This isn't the first time someone's asked for this, and I understand why people would need it, but this is a gnome thing. Jailm8 doesn't have a GUI, so it can't use gnome apps. Sorry
