### ISSUE TITLE
Able to incorporate latest PongoOS bug fix?

### ISSUE THREAD

**Issue by JazzMan808** [Watking01/bootm8#14]
Hi are you able to incorporate the latest PongoOS bug fix into JailM8 which helps with A9X jailbreaking?

**Comment by SarKaa** [comment]
I've never actually heard of the fix for a9, could you send a link, and I'll see what I can do

**Comment by JazzMan808** [comment]
https://github.com/checkra1n/BugTracker/issues/2074

Here you go bud, appreciare it!

**Comment by SarKaa** [comment]
Aight thanks I'll look into it

**Comment by JazzMan808** [comment]
Hey bud it’s no issue. I’ve managed to get checkra1n working on Ubuntu with the fixed pongoOS

up 2 u if you want to add it in your build

**Comment by SarKaa** [comment]
Well the latest checkra1n update does fix it, so it should work now
