### ISSUE TITLE
Successful jailbreak, but boots jailm8 with errors

### ISSUE THREAD

**Issue by thekio1984** [Watking01/bootm8#9]
Not sure if its an issue or what, but using a toshiba satellite l300 laptop (intel celeron t1600 cpu), it works, just shows loadsa things that seem wrong (see attached pic), so far ive managed to jailbreak everytime seemingly fine (even tho checkra1n itself also shows some usb error), just wanted to share in hope they not serious. Thanks though, jailm8 is the only tool (except actually using check on a mac), thats actually worked & on such an old machine. 👍
![898CD5DC-FB71-41D6-A1A7-C6A85F07260C](https://user-images.githubusercontent.com/31554776/101245472-0f8a0600-3705-11eb-9f6d-a7d230cc27e4.jpeg)

**Comment by SarKaa** [comment]
Some of those errors are regarding the machine, so don't worry about them. Some of them are just due to me removing the bulk of the Debian stuff, but neither of these affect jailm8 as a whole.

**Comment by thekio1984** [comment]
> Some of those errors are regarding the machine, so don't worry about them. Some of them are just due to me removing the bulk of the Debian stuff, but neither of these affect jailm8 as a whole.
^---
AWESOME INFO, still working flawlessly, thanks 😊

**Comment by SarKaa** [comment]
No worries bro 👍
